sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic

env:
  global:
    - ROS_DISTRO="indigo"
    - UPSTREAM_WORKSPACE=file
    - BEFORE_SCRIPT=./.travis.install.sh

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - travis_wait 60 .ci_config/travis.sh 
