// ROS message includes
#include "ros/ros.h"
#include <std_msgs/Float64MultiArray.h>
#include <std_srvs/Empty.h>

/* protected region user include files on begin */
#include <iostream>
/* protected region user include files end */

using namespace std;

class sensorTester_node_config
{
public:
};

class sensorTester_node_data
{
// autogenerated: don't touch this class
public:
    //input data
    std_msgs::Float64MultiArray in_test_publish;
    //output data
};

class sensorTester_node_impl
{
    /* protected region user member variables on begin */
    /* protected region user member variables end */

public:

	sensorTester_node_data myInputs;

    sensorTester_node_impl() 
    {
        /* protected region user constructor on begin */
        /* protected region user constructor end */
    }

    void configure(sensorTester_node_config config) 
    {
        /* protected region user configure on begin */
        /* protected region user configure end */
    }

    void update(sensorTester_node_data &data, sensorTester_node_config config)
    {
        /* protected region user update on begin */
    	cout << "I have read: " << myInputs.in_test_publish << endl;
        /* protected region user update end */
    }

    bool callback_testService(std_srvs::Empty::Request  &req, std_srvs::Empty::Response &res , sensorTester_node_config config)
    {
        /* protected region user implementation of service callback for testService on begin */
        /* protected region user implementation of service callback for testService end */
        return true;
    }

    /* protected region user additional functions on begin */
    /* protected region user additional functions end */
};
